version: "3.9"
services:
  front-end:
    build: ./front-end
    container_name: front-end_c
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
  api:
    build: ./api
    container_name: api_c
    image: kermitinbliss/flask_live_app:1.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_APP=base.py
      - FLASK_ENV=development
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
